[package]
name = "tinymap"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
tinyvec = { version = "0.4.1", features = ["nightly_const_generics"] }
